name: Build Intel Mac App
on: [push]

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64' # Aiškiai pasakom GitHubui naudoti Intel Python versiją

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install macholib
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          # Naudojam --codesign-identity - , kad būtų naudojamas paprastas ad-hoc parašas be klaidų
          pyinstaller --noconsole --onefile \
          --target-arch x86_64 \
          --codesign-identity - \
          --name "AttendanceReport" main.py
        
      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Intel-Mac-Attendance-App
          path: dist/AttendanceReport
